name: 'Terraform'
on:
  push:
    branches:
    - "dev"
    - "prod"
permissions:
  contents: read

jobs:
  get-tag:
    runs-on: ubuntu-latest
    outputs:
      tag_version: ${{ steps.get_tag_version.outputs.version }}     
    steps:
     - name: Get the version 
       id: get_tag_version 
       run: |
        echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}
   
  
  Dev_Deployment:
    name: 'Terraform_dev'
    runs-on: ubuntu-latest
    needs: [get-tag]
    if: contains( needs.get-tag.outputs.tag_version , 'dev')
    environment: Dev
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner      
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      env:
       GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform init
      run: |
       cd custom-role/tenants/dev
       terraform init
      env:
       GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}

    - name: Terraform Format
      run: terraform fmt -check

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: |
       cd custom-role/tenants/dev
       terraform plan -input=false -lock=false
      env:
       GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}

      # On push to "main", build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
    - name: Terraform Apply
      run: |
        echo "inside terraform apply"
        cd custom-role/tenants/dev
        terraform apply -auto-approve -input=false
      env:
       GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}

    - name: Do you want to destroy
      shell: bash
      run: |
         auth_header=$(git log --format=%B -n 1 ${{ github.event.after }})
         echo $auth_header
    - name: set environment variables
      uses: allenevans/set-env@v2.0.0
      with:
       MY_ENV_VAR_2: $auth_header

    - name: auth value 
      run: |
       echo $(env.MY_ENV_VAR_2)
   

    - name: Terraform destroy
      if: contains(env.MY_ENV_VAR_2 , 'Terraform Destroy')
      run: |
        echo "inside terraform destroy"
      env:
       GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}
       echo: ${{env.MY_ENV_VAR_2}}
      

  Prod_Deployment:
    name: 'Terraform_Prod'
    runs-on: ubuntu-latest
    needs: [get-tag]
    if: contains( needs.get-tag.outputs.tag_version , 'prod')
    environment: Production

    defaults:
      run:

        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      env: 
        GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}
    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform init
      run: |
        cd custom-role/tenants/prod
        terraform init
      env: 
        GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}  

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: |
        cd custom-role/tenants/prod
        terraform plan -input=false -lock=false
      env: 
        GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}

      # On push to "main", build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
    - name: Terraform Apply
      if: github.base_ref == 'main' && github.event_name == 'pull_request'
      run: |
       cd custom-role/tenants/prod
       terraform apply -auto-approve -input=false
      env: 
        GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}